sudo: required
dist: xenial
language: csharp
mono: none
solution: AspNetCore.Yandex.ObjectStorage.sln
dotnet: 2.2
script:
  - cd AspNetCore.Yandex.ObjectStorage
  - dotnet restore
  - dotnet build -c Release
deploy:
 skip_cleanup: true
 provider: script
 script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
 on:
  branch: master